### ISSUE TITLE
Won't forward for unverified addresses.

### ISSUE THREAD

**Issue by skbach** [arithmetric/aws-lambda-ses-forwarder#5]
Hi there,

Your script only forwards if the email is sent FROM an already verified address.

I'm not running in a sandbox, but SES always seems to think the from address is the original from address when forwarding, and it fails with "Email address is not verified".

If I verify the sender's address in SES, then the script works, but obviously I cannot verify everyone who is going to send me email.

I tried removing the From: original via Recipient in lieu of just From: recipient, but it still fails.  Maybe because of the Reply-To, or maybe because of the Return-Path?  Not sure.

**Comment by arithmetric** [comment]
Hi @skbach,

You should not need to verify the sender for this script, but it's possible the address in another header is being blocked. I just merged #4, which removes the Return-Path from the message. Could you see if this update resolves the issue for you?

**Comment by skbach** [comment]
Weird, I remove the Return-Path yesterday using exactly the same code as you've merged, but my version still fails on unverified recipients.  Your version works, not sure what's different.

Anyway, as someone else mentioned, the version without Return-Path now forwards the original headers inside the body of the mail message.

**Comment by arithmetric** [comment]
@skbach I pushed an change to fix how Return-Path (and Reply-To) are altered. I think this will fix the headers issue.

**Comment by skbach** [comment]
That solves the header problem, but the unverified addresses problem has returned.

If I send from hotmail, it crashes as "unverified".  If I send from yahoo, it works.  I think this approach may be too finicky, since the original headers *may* interfere with aws depending on the original sender.

Abandoning this in favor of constructing the email from scratch with only the pertinent information:
http://devlog.rolandow.com/2016/02/forward-incoming-mail-using-amazon-services-and-lambda/

**Comment by arithmetric** [comment]
If you're seeing unverified issues, I'd suggest reviewing the AWS SES documentation on verifying email addresses: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses.html

Specifically, both the From and Return-Path on emails must be verified. Also, the verification is case sensitive, so if you verify john@example.com, you may not be able to send email that is from John@Example.com.

**Comment by JordanReiter** [comment]
Hi,

I just ran the script today. I went ahead and changed *every single email* in the header so that it was one of my verified email addresses, and I *still* get the unverified email message. As far as I can tell I'm not in the sandbox and I can send outgoing emails everywhere else just fine, I just can't send it from this script.

**Comment by arithmetric** [comment]
Another note on the unverified error: Initially the SES service in every region is in "sandbox" mode, which has several restrictions, including that you may only send email to verified email addresses or domains.

See: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

Therefore, if the SES service is in sandbox mode, the email address that you are forwarding to must be verified, as well as the email address for which you are receiving and forwarding.

**Comment by skbach** [comment]
Even outside of sandbox the problem persists.   I had to build the email
headers from scratch....simply regex replacing the original email never
worked for me.
